Casper\AttachmentBundle\Entity\AbstractSingleAttachment:
    type: mappedSuperclass

    lifecycleCallbacks:
        prePersist:  [ preUpload ]
        preUpdate:   [ preUpload ]
        postPersist: [ upload ]
        postUpdate:  [ upload ]
        postRemove:  [ removeUpload ]

    fields:
        filename:
            type: string
            length: 255
        path:
            type: string
            length: 255
