Casper\AttachmentBundle\Entity\AbstractMultiAttachment:
    type: mappedSuperclass

    fields:
        isPrimary:
            type: boolean
            nullable: false
            default: false

    # It should be copied and overridden in child entity
#    manyToOne:
#        holder:
#            targetEntity: Casper\AttachmentBundle\Entity\AbstractAttachmentContainer